# -*- coding: utf-8 -*-
"""Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/nepatiess/Python-Notes/blob/main/Python.ipynb

## Introduction
"""

help()

fav_number = 13
if fav_number < 15:
    print("My favourite number is smaller than 15")

pi = 3.14
print(pi)

#obviously this function shows a greeting message according to the given name :)
def greetings(name):
  print(f'Hello, {name}')

pi = 3.14
if pi < 3.15:
  pi = pi + 0.1

  print(pi)

def greeting(name):
  print('Hello ' + name)
greeting('Zeynep')

"""
This is a long comment that can make the code harder to read on a small screen,
 so it needs to be broken into multiple lines using triple-quotes instead of
 putting a hash symbol in front of each line
"""
def greetings(name):
  print(f'Hello, {name}')

name = 'Zeynep'
name

import datetime
dir(datetime)

today = datetime.date.today()
age = today.year - 2003

print(name)
print(age)

print(type(name))
print(type(age))

name = 'Zeynep'
type(name)

age = 35
type(age)

pi = 3.14
type(pi)

#Store_items =     0      1       2     3     4      5       6       7
store_items = ['Apple', 1.46, 'Banana', 1, 'Milk', 2.99, 'Cheese', 4.49]
print(store_items, type(store_items))
#There are 8 elements in list.
print(len(store_items))

#2. item
print(store_items[2])

#0'dan 4'e kadar olan itemlar
print(store_items[0:4])

#2'den sonuna kadar olan itemlar
print(store_items[2:])

#en baştan 2'ye kadar olan itemlar
print(store_items[:2])

store_items[2] = 'Chocolate'
print(store_items)

age = 21
age += 0.5
print(age, type(age))

age = '41'
type(age)

age = int(age)
print(age, type(age))

print("Hi, this is Python")

name = "Zeynep"
print(name)

name = "Zeynep"
print("Hello", name)

print(15)

name = input('Name:')
print('Greetings', name)

#Bu kod çalışmıyor çünkü number'ın int olduğunu belirlemedik.
number = input('Number:')
print(number + 10)

number = int(input('Number:'))
print(number + 10)

import math

floor_number = (math.floor(3.45))
print(floor_number, type(floor_number))

import datetime
print(datetime.datetime.now())

import random
print(random.randint(1,6))

"""## Python Syntax"""

print(2+5)

print("5+2=",5+2)
print("5-2=",5-2)
print("5*2=",5*2)
print("5/2=",5/2)
print("5%2=",5%2)
print("5**2=",5**2)
print("5//2=",5//2)

x = 5 #equivalent to x = 5
x += 5 #equivalent to x = x+5
x-= 5 #equivalent to x = x-5
x *= 5 #equivalent to x = x*5
x /= 5 #equivalent to x = x/5
x %= 5 #equivalent to x = x%5
x //= 5 #equivalent to x = x//5
x **= 5 #equivalent to x = x**

num1 = 10
num2 = 5

print(num1, ">", num2, "=", num1 > num2)
print(num1, ">=", num2, "=", num1 >= num2)
print(num1, "<", num2, "=", num1 < num2)
print(num1, "<=", num2, "=", num1 <= num2)
print(num1, "==", num2, "=", num1 == num2)
print(num1, "!=", num2, "=", num1 != num2)

print("True and True =", True and True)         # 1 ^ 1 = 1
print("True and False =", True and False)       # 1 ^ 0 = 0
print("False and True =", False and True)       # 0 ^ 1 = 0
print("False and False =", False and False)     # 0 ^ 0 = 0

print("True or True =", True or True)           # 1 v 1 = 1
print("True or False =", True or False)         # 1 v 0 = 1
print("False or True =", False or True)         # 0 v 1 = 1
print("False or False =", False or False)       # 0 v 0 = 0

print("not True =", not True)                   # not 1 = 0
print("not False =", not False)                 # not 0 = 1

"""### Practical Exercise 1:Plan an exciting adventure with a new friend"""

message = "Hello, my name is Python! Nice to meet you. What is yours?"
print(message)

answer = "Hi, my name is Zeynep! Nice to meet you too."
print(answer)

today = datetime.date.today()
my_age = today.year - 2003
my_height = 1.55
my_hair_color = "brown"
my_eye_color = "brown"
my_hometown = "Turkey"
where_i_live = "İstanbul"

print("I am", str(my_age), "years old.")
print("I am", str(my_height), "meters tall.")
print("I have", my_hair_color, "hair.")
print("I have", my_eye_color, "eyes.")
print("I am from", my_hometown, ".")
print("I live in", where_i_live)

favourite_places_foods = ["Paris", "Milan", "Barcelona", "Berlin", "Vegas", "Croissant", "Pasta", "Pizza"]
print(favourite_places_foods)

favourite_places = favourite_places_foods[0:5] #select all the places (Another option [:5])
favourite_food = favourite_places_foods[5:10] #select all the foods (Another option [5:])

#Select the first and last three from place and food lists
first_three_places=favourite_places[0:3]
last_three_foods =favourite_food[2:5]

#Print both lists
print(first_three_places)
print(last_three_foods)

import random
a = random.randint(0,2)

meeting_place = first_three_places[a]

print(meeting_place)

first_activity = "lets play chess in the park"
second_activity = "lets play a game at the internet cafe"
third_activity = "lets go to the museum in Konuralp"

#Write your and Ömer's preference for each activity either as "True" or "False"

#First activity
first_activity_your = True
first_activity_friend = False

#Example statement
print("We are going to play chess in the park! Answer:" ,first_activity_your and first_activity_friend)

#Second activity
second_activity_your = True
second_activity_friend = True

#Your turn to write the statement
print("We are going to play a game of tennis. Answer:" ,second_activity_your and second_activity_friend)

#Third activity
second_activity_your = False
second_activity_friend = False

print("At least one of us is going to the museum. Answer:" ,second_activity_your or second_activity_friend)

meeting_date = input('In which month do you want to do on our fun adventure?: ')
meeting_food = input('What do you want to eat?: ')
meeting_place = input('Where do you want to go?: ')
print("We are going to", meeting_place, "and we will eat", meeting_food, "in", meeting_date)

"""## Flow Controls"""

celcius = 25
if celcius > 20:
  print('Good')

celcius = 18
if celcius > 20:
  print('Good')

celcius = 18
if celcius > 20:
  print('Good')
else:
  print('Cold')

celcius = 32
if celcius > 30:
  print('Hot')
  if celcius > 20:
    print('Good')
  else:
    print('Cold')

celcius = 32
if celcius > 30:
  print('Hot')
elif celcius > 20:
  print('Good')
else:
  print('Cold')

celcius = 32
if celcius > 30:
  print('Hot')
elif 30 >= celcius > 20:
  print('Good')
elif -273 < celcius <= 20:
  print('Cold')
else:
  print('Something went wrong!')

drivers_licence = True
age = 17

if age > 17:
  if drivers_licence:
    print('You can drive car')
  else:
    print('You need to go to a drivers licence course')
else:
  print('You need to get older')

print('E')
print('l')
print('e')
print('m')
print('e')
print('n')
print('t')
print('e')
print('r')

name = 'Elementer'
for i in name:
  print(i)
print('Loop is completed.')

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
for i in numbers:
  print(i)

print('Loop is completed.')

for i in range(5,21):
  print(i)
print('Loop is completed.')

for i in range(1,101):
  if i % 5 == 0:
    print(i)
print('Loop has been completed')

celcius = 10
if celcius > 30:
  print('Hot')
elif 30 >= celcius > 20:
  print('Good')
elif -273 < celcius <= 20:
  print('Cold')
else:
  print('Something went wrong!')

celcius = 10

while celcius < 50:

  if celcius > 30:
    print('Hot')
  elif 30 >= celcius > 20:
    print('Good')
  elif -273 < celcius <= 20:
    print('Cold')
  else:
    print('Something went wrong!')
  celcius += 5

celcius = 10

while celcius < 50:

  if celcius > 30:
    print('Hot')
  elif 30 >= celcius > 20:
    print('Good')
  elif -273 < celcius <= 20:
    print('Cold')
  else:
    print('Something went wrong!')
  print('The current temperature is',celcius)
  celcius += 5

import time
celcius = 10

while celcius < 50:

  if celcius > 30:
    print('Hot')
  elif 30 >= celcius > 20:
    print('Good')
  elif -273 < celcius <= 20:
    print('Cold')
  else:
    print('Something went wrong!')
  print('The current temperature is',celcius)
  celcius += 5
  time.sleep(1)

#Infinite loop
while True:
  print('I love you!')

import time
counter = 0

while counter >= 0:
  counter += 1

  print(counter)
  time.sleep(1)

import random
while True:
  random_number = random.randrange(100)
  print(random_number)

  if random_number == 77:
    print('Found!')
    break

names = ['Max', 'Felix', 'Alisha', 'Lucas', 26, 'Sarah']

for name in names:
  if type(name) != str:
    print('Found', name)
    break

  else:
    print(name, 'is a string.')

"""### Practical Exercise 2: I am a game developer :)"""

import random

# Taş, Kağıt, Makas listesini oluştur
actions = ['rock', 'paper', 'scissors']

# Oyuncuların skorlarını sıfırla
player1_score = 0
player2_score = 0

# Kullanıcıdan kaç tur oynanacağını sor
num_rounds = int(input("Kaç tur oynamak istiyorsunuz? "))

# Belirtilen tur sayısı kadar oyunu oynayan bir döngü yaz
for round in range(1, num_rounds + 1):
    print(f"{round}. Tur:")

    # Her iki oyuncu için rastgele bir seçim yap
    player1_choice = random.choice(actions)
    player2_choice = random.choice(actions)

    # Oyuncuların seçimlerini yazdır
    print(f"1. Oyuncu seçimi: {player1_choice}")
    print(f"2. Oyuncu seçimi: {player2_choice}")

    # Turun kazananını belirle
    if player1_choice == player2_choice:
        print("Berabere!")
    elif (player1_choice == 'rock' and player2_choice == 'scissors') or \
         (player1_choice == 'paper' and player2_choice == 'rock') or \
         (player1_choice == 'scissors' and player2_choice == 'paper'):
        print("1. Oyuncu bu turu kazandı!")
        player1_score += 1
    else:
        print("2. Oyuncu bu turu kazandı!")
        player2_score += 1

    # Skoru yazdır
    print(f"Skor - 1. Oyuncu: {player1_score}, 2. Oyuncu: {player2_score}")
    print()

# Tüm turlar tamamlandıktan sonra nihai sonuçları yazdır
print("Nihai Skor:")
print(f"1. Oyuncu: {player1_score}, 2. Oyuncu: {player2_score}")
if player1_score > player2_score:
    print("Tebrikler! 1. Oyuncu kazandı!")
elif player2_score > player1_score:
    print("Tebrikler! 2. Oyuncu kazandı!")
else:
    print("Oyun berabere bitti!")

"""## Functions"""

number = '15'
print('Type of number before int() function: ', type(number))
print(number)
number = int(number)
print('Type of number after int() function: ', type(number))
print(number)

def hello(name):
  print('Hello', name)

hello('Zeynep')

def sum(num1, num2):
  print(num1 + num2)

sum(3 , 5)

result = sum(3 , 5)
print(result)

def sum(num1, num2):
  answer = num1 + num2
  return answer

result = sum(3 , 5)
print(result)

def argument_printer(arg_position1, arg_position2):
  print('Argument at position 1: ', arg_position1)
  print('Argument at position 2: ', arg_position2)

argument_printer('value 1', 'value 2')

argument_printer()

def greetings(first_name, last_name, auto_correction):
  if auto_correction == True:
    capitalized_first_name = first_name.capitalize()
    capitalized_last_name = last_name.capitalize()
    print("Hello,", capitalized_first_name, capitalized_last_name)
  else:
    print("Hello,", first_name, last_name)

greetings('zEyNEp', 'kOz', True)

greetings('zEyNEp', 'kOz', False)

def greetings(first_name, last_name, auto_correction = True):
  if auto_correction == True:
    capitalized_first_name = first_name.capitalize()
    capitalized_last_name = last_name.capitalize()
    print("Hello,", capitalized_first_name, capitalized_last_name)
  else:
    print("Hello,", first_name, last_name)

greetings('zEyNEp', 'kOz')

def car(brand, model, color):
  print('My favourite car is the', brand, model, 'in the color', color)

car('Chevrolet', 'Camaro', 'Black')

car(color = 'Black', brand = 'Chevrolet', model = 'Camaro')

car(color = 'Chevrolet', model = 'Camaro', 'black')

number = 13 #Global Variable
def change_number():
  number = 4 #Local Variable

change_number()
print(number)

number = 13
def change_number():
  global number
  number = 4

change_number()
print(number)

#number = 13

def change_number():
 num = 4

change_number()
print(num)

#Write following method in the test.py file
"""
test.py module
This is a test module to print a message to the screen
"""
def greetings(name):
  print('Hello', name)

import test

test.greetings('Zeynep')

pip install seaborn

import seaborn as sns

import seaborn as sns
import matplotlib.pyplot as plt

data = [1, 2, 10, 3, 5, 6, 13, 8]

# x ve y eksenlerini anahtar kelimelerle belirtin
sns.lineplot(x=range(8), y=data)

plt.show()

"""### Practical Exercise 3: Help Julia on her trip to New York"""

def greetings(name):
  print('Hello', name)

greetings('Sam')

def difference(num1, num2):
  print(num1 - num2)

difference(25, 14)

#Run this cell to store Julia's personal information in variables
birthday = "4 September 1996"
place_of_birth = "London"
current_city = "London"

def introduction(name, birthday, place_of_birth, current_city):
  print("Hello, my name is", name, "I was born on", birthday, "in", place_of_birth)

introduction('Julia', '4 September 1996', 'London', 'London')

def change_current_city():
  global current_city
  current_city = "New York"

change_current_city()
print(current_city)

#We need to import the seaborn library
import seaborn as sns
import matplotlib.pyplot as plt
#Weather Data
day = [1, 2, 3, 4, 5, 6, 7]
avg_temp = [14, 9, 3, 11, 18, 27, 6]

#Create a bar plot for the given data
sns.barplot(x=day, y=avg_temp)

#Show the plot
plt.show()

#import library
import math

def miles_to_km(miles):
  km = miles * 1.60934
  return km

def km_to_miles(km):
  miles = km / 1.60934
  return miles

assert math.isclose(miles_to_km(132.2), 212.754748, abs_tol = 1e-5), "Test failed for mile_to_km"
assert math.isclose(km_to_miles(48.44), 30.099295, abs_tol = 1e-5), "Test failed for km_to_mile"
print("Test passed!")

miles_to_km(12)

def pound_to_kg(quantity, mode):
  assert mode == "pound2kg" or mode == "kg2pound", "Invalid argument!"
#Here the assert command ensures that a valid mode is given as argument.

  #Write a statement to convert pound to kilogram for mode "pound2kg"
  if mode == "pound2kg":
    print(quantity * 0.453592)

  #Else it should convert kilogram to pound.
  else:
    print(quantity / 0.453592)

def fahrenheit_celcius(temperature, mode):
  assert mode == "f2c" or mode == "c2f", "Invalid argument!"
  # Write a statement to convert Fahrenheit to Celsius or Celsius to Fahrenheit

  if mode == "f2c":
    print((temperature - 32) * 5/9)
  else:
    print(temperature * 9/5 + 32)

fahrenheit_celcius(88, "f2c")

"""## Data Structures"""

shopping_list = ["Apple", "Juice", "Ball", "Book"]

#Listenin sonuna "Water" eklendi
shopping_list.append("Water")
print(shopping_list)

#Listenin 2. indexine "Banana" eklendi
shopping_list.insert(2, "Banana")
print(shopping_list)

#"Apple" indexi listeden silindi
shopping_list.remove("Apple")
print(shopping_list)

#Listenin 3. indexi "Strawberry" oldu
shopping_list[3] = "Strawberry"
print(shopping_list)

number_list = [1, 2, 3, 4, 5]

square_list = []

for num in number_list:
  square_list.append(num ** 2)

print(square_list)

number_list = [1, 2, 3, 4, 5]
square_list = [num ** 2 for num in number_list]

print(square_list)

shopping_list = ["Apple", "Juice", "Ball", "Book"]

item1, item2, item3, item4 = shopping_list
print(item1)
print(item2)
print(item3)
print(item4)

print(shopping_list[0])

#1'den 3'e kadar
print(shopping_list[1:3])

shopping_list[1] = "Water"

phone_book = {'Zeynep':'+90 505 123 45 67', 'Home phone':'+1 234 235 5678'}
print(phone_book)

print(phone_book['Zeynep'])

inventory = dict()
inventory['bananas'] = 25
inventory['apples'] = 102
inventory['oranges'] = 54
inventory['watermelons'] = 4

print(inventory)

print(inventory['apples'])

print(inventory.keys())

print(inventory.values())

print(inventory.items())

for element in inventory:
  print(element)

for key in inventory:
  inventory[key] += 100

print(inventory)

for key, value in inventory.items():
  if value > 200:
    print('Too many', key)
  else:
    print('Enough', key)

"""### Practical Exercise 4: My own supermarket"""

#Create a shopping list
shopping_list = ['Biscuit', 'Coffee', 'Milk', 'Egg']

#Use the append method to add bananas to your list
shopping_list.append('Bananas')

#Print your shopping list
print(shopping_list)

#Use insert method to add onions at a specific position in your list
shopping_list.insert(3, 'Onions')

#Print your shopping list
print(shopping_list)

shopping_list.append('Potatoes')
#Use the remove method to remove potatoes from the list
shopping_list.remove('Potatoes')

#Print your shopping list
print(shopping_list)

"""## Files and Errors"""

import os

os.makedirs('/content/file_operations', exist_ok=True)

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/file_operations

message_file = open('message.txt', 'r')
print(message_file.read())
message_file.close()

hello_file = open('hello.txt', "w")

hello_file.write('Hello World, this is Python')
hello_file.close()

import random
while True:
  random_number = random.randrange(100)
  print(random_number)

  if random_number == 77:
    print('Found!')
    break

import random

numbers_file = open('numbers.txt', 'w')

while True:
  random_number = random.randrange(100)
  print(random_number)
  numbers_file.write(str(random_number))
  numbers_file.write('\n')

  if random_number == 77:
    print('Found!')
    numbers_file.write('Found!')
    numbers_file.close()
    break

import random

with open('number_history.txt', 'w') as number_file:

  while True:
    random_number = random.randrange(100)
    print(random_number)
    number_file.write(str(random_number))
    number_file.write('\n')

    if random_number == 77:
      print('Found!')
      number_file.write('Found!')
      break

number1 = 15
number2 = input('Please enter a number: ')
print(number1 + number2)

celcius = 18
if celcius > 20:
  print('Good')
  else:
    print('Cold')

def divide(number1, number2):
  number1_integer = int(number1)
  number2_integer = int(number2)
  return number1_integer / number2_integer

number1 = input('Please provide number 1: ')
number2 = input('Please provide number 2: ')

print(divide(number1, number2))

def divide(number1, number2):
   try:
       number1_integer = int(number1)
       number2_integer = int(number2)
       return number1_integer / number2_integer

   except:
       return 'Only integers are allowed! Try again.'

number1 = input('Please provide a number1: ')
number2 = input('Please provide a number2: ')

print(divide(number1, number2))

def divide(number1, number2):
   try:
       number1_integer = int(number1)
       number2_integer = int(number2)
       return number1_integer / number2_integer

   except ValueError:
       return 'Only integers are allowed!'

   except ZeroDivisionError:
       return 'You cannot divide any number by zero!'



number1 = input('Please provide a number1: ')
number2 = input('Please provide a number2: ')

print(divide(number1, number2))

"""### Practical exercise 5: Become a teacher assistant"""

#Define a function compute_grade that takes points as an argument and returns the grade as a letter
def compute_grade(points):
  if points >= 70:
    return 'A'
  elif points >= 50:
    return 'B'
  elif points >= 30:
    return 'C'
  else:
    return 'F'

#Call the function to convert 39 points to a letter grade
compute_grade(39)

#Define a function that takes the student name and the points as an argument and the points as an argument and returns the message for the report card
def report_message(name, points):
  return name + " scored" + str(points) + "/100 points in Chemistry and got the letter " + compute_grade(points) + "."

#Call the function for you friend Zach
report_message('Zach', 51)

#Create a text file for Zach's report card and write the message inside
result_file = open('zach_card.txt', 'w')
result_file.write(report_message('Zach', 51))
result_file.close()

#Check if there is already a report card for Sophie and print a message in case there is
try:
  result_file = open("sophie_report.txt", 'r')
  print('There is an existing report card for Sophie')
#If there is none, create one and write the message inside
except:
  result_file = open("sophie_report.txt", 'w')
  result_file.write(report_message("Sophie", 78))

result_file.close()

#Define a function that takes the student name and the points as an argument and returns them as specified in the instructions
def student_grade(name, points):
  #return name:grade
  try:
    return (name + ':' + compute_grade(points))
  #or return a message if the student was missing
  except:
    return (name + ' was missing during the exam.')

#Run the list of all students and their points
student_list = [('Zach', 51), ('Sophie', 78), ('Fred', 29), ('Belina','missing'), ('Markus','missing')]

#Write a for loop to access each student one at a time and unpack the tuple
for name, points in student_list:
  grade = student_grade(name, points)
  #print the message returned by student_grade
  print(grade)

#Create the grades.txt file
grades_file = open("grades.txt", 'w')

#Use the for loop to write the name and grade of each student in the file
for name, points in student_list:
  grade = student_grade(name, points)
  #Write the message returned by student_grade into the file
  grades_file.write(grade + '\n')

#Close the file
grades_file.close()